name: hello world workflow
on:
  push:
    branches:
     - main
  pull_request:
    branches:   
      - main
  workflow_dispatch:


jobs:
  hello:
    runs-on: self-hosted
    steps:
      
      - uses : actions/checkout@v2
      - name: hell world
        run: echo "hello world"
        shell: bash
  goodbye:
    runs-on: self-hosted
    steps:
      - name: goodbye world
        run: ls -la
        shell: bash    

              
